### ISSUE TITLE
MD5 Hash generation problem

### ISSUE THREAD

**Issue by okal** [kenliu/grails-elastic-beanstalk#4]
Hi Ken,

I'm using v0.1.1, with Grails 2.0.3 (It's what we use for our product). Getting the following error after running `grails aws-eb-deploy`.

```
Error executing script AwsEbDeploy: com.amazonaws.AmazonClientException: Unable to calculate MD5 hash: /home/okal/projects/monitorious/target/monitorious-0.4.war (No such file or directory)
```

Any idea what could be causing that?

**Comment by okal** [comment]
Sorry, I was being a little dumb. I'd bumped up the app version but didn't actually create a WAR file.

**Comment by kenliu** [comment]
The script really should give some kind of error message if the WAR file is missing though. Will have some improved error handling in the upcoming releases.

**Comment by kenliu** [comment]
BTW, would love to hear any feedback on how the plugin is working out for you.
