### ISSUE TITLE
Endpoint URL Settings does not work

### ISSUE THREAD

**Issue by chongivan** [kenliu/grails-elastic-beanstalk#8]
grails.plugin.awsElasticBeanstalk.serviceEndpointUrl = 'elasticbeanstalk.ap-southeast-1.amazonaws.com'

in Config.groovy does not change the EndpointUrl.

**Comment by kenliu** [comment]
The full URL needs to be specified, for example:

```
grails.plugin.awsElasticBeanstalk.serviceEndpointUrl = 'https://elasticbeanstalk.ap-southeast-1.amazonaws.com'
```

Let me know if that works out for you, if not I'll investigate further.

**Comment by chongivan** [comment]
Hey Bro,
grails.plugin.awsElasticBeanstalk.serviceEndpointUrl = 'https://elasticbeanstalk.ap-southeast-1.amazonaws.com'
doesn't work =(

I even set
export ELASTICBEANSTALK_URL=https://elasticbeanstalk.ap-southeast-1.amazonaws.com
for the environment variable.

**Comment by kenliu** [comment]
OK, thanks I'll investigate further.

Could you share any information that might be helpful - e.g. Grails version, OS version, java version, etc.?

**Comment by chongivan** [comment]
OS X 10.8.4
Grails 2.2.3
java version "1.6.0_51"
Java(TM) SE Runtime Environment (build 1.6.0_51-b11-457-11M4509)
Java HotSpot(TM) 64-Bit Server VM (build 20.51-b01-457, mixed mode)

Im also using 
runtime ':aws-sdk:1.5.5'

**Comment by kenliu** [comment]
Thanks. It's possible that the aws-sdk plugin is somehow causing a conflict here. I haven't tried running it together with the elastic beanstalk plugin.

**Comment by kenliu** [comment]
Hi -

I was able to deploy to Elastic Beanstalk ap-southeast-1 region on Grails 2.2.3, even with the aws-sdk plugin installed. Are you sure you are running the latest version of the plugin (0.2)?

Also, when you say that it "doesn't work", can you be more specific?

Did the plugin output an error message? Did you see anything happening in the AWS web console when you were running the script? You should see some output from aws-eb-deploy that looks something like this:

```
loading AWS credentials
Loading credential file from: /Users/kenliu/code/aws elastic beanstalk/grails-test-app/credentials.properties
initializing ElasticBeanstalk client
WAR file name: /Users/kenliu/code/aws elastic beanstalk/grails-test-app/testapp-2.2/target/testapp-0.1.war
Starting AWS Elastic Beanstalk deployment
Finding S3 bucket to upload WAR
Uploading local WAR file testapp-0.1.war to remote WAR file: 141768d8480-testapp-0.1.war
Uploading WAR to S3 bucket elasticbeanstalk-ap-southeast-1-419688207252
```

**Comment by chongivan** [comment]
Hey, this is my output:

Loading credential file from: /Users/Ivan/Dropbox/aws/aws_credential_file
script metadata: [app.version:0.1, app.grails.version:2.2.3, app.name:ChatServer2]
Grails settings warname /Users/Ivan/Dropbox/co/ChatServer2/target/ChatServer2-0.1.war
WAR file name: /Users/Ivan/Dropbox/co/ChatServer2/target/ChatServer2-0.1.war
Starting AWS Elastic Beanstalk deployment
Finding S3 bucket to upload WAR
Uploading local WAR file ChatServer2-0.1.war to remote WAR file: 141773a7208-ChatServer2-0.1.war
Uploading WAR to S3 bucket elasticbeanstalk-us-east-1-551207789056

//you see here that it is deploying to us-east
//and naturally the rest should fail coz i didnt create any application at us-east.

Uploaded WAR to S3
Create application version with uploaded application
applicationName: ChatServer
environmentName: chatserver-env
version label: 2013-10-02_04-27-01
versionLabel: 2013-10-02_04-27-01
Created application version {ApplicationVersion: {ApplicationName: ChatServer,Description: Deployed on Wed Oct 02 04:30:23 SGT 2013 from Grails AWS Elastic Beanstalk Plugin,VersionLabel: 2013-10-02_04-27-01,SourceBundle: {S3Bucket: elasticbeanstalk-us-east-1-551337789056,S3Key: 14225b3d218-ChatServer2-0.1.war},DateCreated: Wed Oct 02 04:30:25 SGT 2013,DateUpdated: Wed Oct 02 04:30:25 SGT 2013}}
Updating environment with uploaded application version
| Error Error executing script AwsEbDeploy: AmazonServiceException: Status Code: 400, AWS Service: AWSElasticBeanstalk, AWS Request ID: 4e30563f-2ad8-11e3-b3fd-17218ed82eca, AWS Error Code: InvalidParameterValue, AWS Error Message: No Environment found for EnvironmentName = 'chatserver-env'. (Use --stacktrace to see the full trace)

I can conclude that the problem lies in the setting of the EndpointURL T_T

**Comment by chongivan** [comment]
I've also noticed a discrepancy between the plugin dependencies found:
at http://grails.org/plugin/aws-elastic-beanstalk, it says compile ":aws-elastic-beanstalk:0.2"
at https://github.com/kenliu/grails-elastic-beanstalk however, it says build ':aws-elastic-beanstalk:0.1.1'

I've tried both, not working T_T

**Comment by chongivan** [comment]
It works for a newly created grails app bro. Guess we can close this issue now?

**Comment by kenliu** [comment]
I see what's going on, the dependency should be:

```
plugins {
    build ":aws-elastic-beanstalk:0.2"
}
```

If this doesn't work, try:

```
grails clean
grails war
grails aws-eb-deploy
```

Looks like your app is using version 0.1.1 of the plugin, which didn't yet support alternate regions.  The grails plugin portal puts bad installation information by default, and the doc on github is out of date.

Sorry for the inconvenience.
