### ISSUE TITLE
Nullpointer Exception in Grails 2.2.3 when doing aws-eb-deploy

### ISSUE THREAD

**Issue by cc5tudio** [kenliu/grails-elastic-beanstalk#9]
I'm getting the following exception after issuing the deployment command "aws-eb-deploy":

Loading Grails 2.2.3
| Environment set to development.....
| Compiling 1 source files...
loading AWS credentials
Loading credential file from: null
Loading credentials from System properties
initializing ElasticBeanstalk client
WAR file name: /Users/charles/plang/REST-API-Console/target/REST-API-Console-0.1.war
Starting AWS Elastic Beanstalk deployment
Finding S3 bucket to upload WAR
| Error java.lang.NullPointerException
| Error     at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
| Error     at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
| Error     at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
| Error     at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
| Error     at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:77)
| Error     at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:102)
| Error     at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:194)
| Error     at gant.Gant$_dispatch_closure5.doCall(Gant.groovy:391)
| Error     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
| Error     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
| Error     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
| Error     at java.lang.reflect.Method.invoke(Method.java:606)
| Error     at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:272)
| Error     at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.call(PogoMetaMethodSite.java:64)
| Error     at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
| Error     at gant.Gant$_dispatch_closure7.doCall(Gant.groovy:415)
| Error     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
| Error     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
| Error     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
| Error     at java.lang.reflect.Method.invoke(Method.java:606)
| Error     at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSite.invoke(PogoMetaMethodSite.java:231)
| Error     at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:52)
| Error     at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:141)
| Error     at gant.Gant$_dispatch_closure7.doCall(Gant.groovy)
| Error     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
| Error     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
| Error     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
| Error     at java.lang.reflect.Method.invoke(Method.java:606)
| Error     at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:272)
| Error     at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.call(PogoMetaMethodSite.java:64)
| Error     at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:112)
| Error     at gant.Gant.withBuildListeners(Gant.groovy:427)
| Error     at gant.Gant.this$2$withBuildListeners(Gant.groovy)
| Error     at gant.Gant$this$2$withBuildListeners.callCurrent(Unknown Source)
| Error     at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:49)
| Error     at gant.Gant$this$2$withBuildListeners.callCurrent(Unknown Source)
| Error     at gant.Gant.dispatch(Gant.groovy:415)
| Error     at gant.Gant.this$2$dispatch(Gant.groovy)
| Error     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
| Error     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
| Error     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
| Error     at java.lang.reflect.Method.invoke(Method.java:606)
| Error     at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
| Error     at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233)
| Error     at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1082)
| Error     at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1106)
| Error     at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:906)
| Error     at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:729)
| Error     at gant.Gant.invokeMethod(Gant.groovy)
| Error     at groovy.lang.GroovyObject$invokeMethod.callCurrent(Unknown Source)
| Error     at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:49)
| Error     at groovy.lang.GroovyObject$invokeMethod.callCurrent(Unknown Source)
| Error     at gant.Gant.executeTargets(Gant.groovy:591)
| Error     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
| Error     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
| Error     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
| Error     at java.lang.reflect.Method.invoke(Method.java:606)
| Error     at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSite.invoke(PogoMetaMethodSite.java:231)
| Error     at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:52)
| Error     at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:49)
| Error     at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:57)
| Error     at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:145)
| Error     at gant.Gant.executeTargets(Gant.groovy:590)
| Error     at org.codehaus.groovy.grails.cli.GrailsScriptRunner.executeWithGantInstance(GrailsScriptRunner.java:769)
| Error     at org.codehaus.groovy.grails.cli.GrailsScriptRunner.executeScriptFile(GrailsScriptRunner.java:567)
| Error     at org.codehaus.groovy.grails.cli.GrailsScriptRunner.executeScriptWithCaching(GrailsScriptRunner.java:466)
| Error     at org.codehaus.groovy.grails.cli.GrailsScriptRunner.executeScriptWithCaching(GrailsScriptRunner.java:417)
| Error     at org.grails.ide.api.impl.GrailsConnectorImpl.executeCommand(GrailsConnectorImpl.java:156)
| Error     at org.grails.ide.eclipse.longrunning.process.GrailsProcess.run(GrailsProcess.java:130)
| Error     at org.grails.ide.eclipse.longrunning.process.GrailsProcess.main(GrailsProcess.java:93)
| Error     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
| Error     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
| Error     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
| Error     at java.lang.reflect.Method.invoke(Method.java:606)
| Error     at org.codehaus.groovy.grails.cli.support.GrailsStarter.rootLoader(GrailsStarter.java:234)
| Error     at org.codehaus.groovy.grails.cli.support.GrailsStarter.main(GrailsStarter.java:262)
| Error Caused by: java.lang.NullPointerException
| Error     at com.amazonaws.services.elasticbeanstalk.AWSElasticBeanstalkClient.invoke(AWSElasticBeanstalkClient.java:1370)
| Error     at com.amazonaws.services.elasticbeanstalk.AWSElasticBeanstalkClient.createStorageLocation(AWSElasticBeanstalkClient.java:371)
| Error     at com.amazonaws.services.elasticbeanstalk.AWSElasticBeanstalkClient.createStorageLocation(AWSElasticBeanstalkClient.java:1165)
| Error     at com.amazonaws.services.elasticbeanstalk.AWSElasticBeanstalk$createStorageLocation.call(Unknown Source)
| Error     at AwsEbDeploy$_run_closure1.doCall(AwsEbDeploy:69)
| Error     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
| Error     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
| Error     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
| Error     at java.lang.reflect.Method.invoke(Method.java:606)
| Error     at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
| Error     at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233)
| Error     at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1082)
| Error     at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1106)
| Error     at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:906)
| Error     at groovy.lang.DelegatingMetaClass.invokeMethod(DelegatingMetaClass.java:149)
| Error     at org.codehaus.gant.GantMetaClass.invokeMethod(GantMetaClass.java:133)
| Error     at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:39)
| Error     at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
| Error     at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:54)
| Error     at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
| Error     at org.codehaus.gant.GantBinding$_initializeGantBinding_closure5_closure16_closure18.doCall(GantBinding.groovy:185)
| Error     at sun.reflect.GeneratedMethodAccessor127.invoke(Unknown Source)
| Error     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
| Error     at java.lang.reflect.Method.invoke(Method.java:606)
| Error     at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSite.invoke(PogoMetaMethodSite.java:231)
| Error     at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:52)
| Error     at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:141)
| Error     at org.codehaus.gant.GantBinding$_initializeGantBinding_closure5_closure16_closure18.doCall(GantBinding.groovy)
| Error     at sun.reflect.GeneratedMethodAccessor126.invoke(Unknown Source)
| Error     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
| Error     at java.lang.reflect.Method.invoke(Method.java:606)
| Error     at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:272)
| Error     at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.call(PogoMetaMethodSite.java:64)
| Error     at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:112)
| Error     at org.codehaus.gant.GantBinding.withTargetEvent(GantBinding.groovy:90)
| Error     at org.codehaus.gant.GantBinding.this$4$withTargetEvent(GantBinding.groovy)
| Error     at sun.reflect.GeneratedMethodAccessor121.invoke(Unknown Source)
| Error     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
| Error     at java.lang.reflect.Method.invoke(Method.java:606)
| Error     at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
| Error     at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233)
| Error     at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1082)
| Error     at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1106)
| Error     at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:906)
| Error     at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1027)
| Error     at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1106)
| Error     at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:906)
| Error     at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:727)
| Error     at groovy.lang.GroovyObjectSupport.invokeMethod(GroovyObjectSupport.java:44)
| Error     at groovy.lang.MetaClassImpl.invokeMethodOnGroovyObject(MetaClassImpl.java:1147)
| Error     at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
| Error     at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1106)
| Error     at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:906)
| Error     at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:66)
| Error     at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:149)
| Error     at org.codehaus.gant.GantBinding$_initializeGantBinding_closure5_closure16.doCall(GantBinding.groovy:185)
| Error     at sun.reflect.GeneratedMethodAccessor120.invoke(Unknown Source)
| Error     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
| Error     at java.lang.reflect.Method.invoke(Method.java:606)
| Error     at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSite.invoke(PogoMetaMethodSite.java:231)
| Error     at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:52)
| Error     at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:141)
| Error     at org.codehaus.gant.GantBinding$_initializeGantBinding_closure5_closure16.doCall(GantBinding.groovy)
| Error     at sun.reflect.GeneratedMethodAccessor119.invoke(Unknown Source)
| Error     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
| Error     at java.lang.reflect.Method.invoke(Method.java:606)
| Error     at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:272)
| Error     at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.call(PogoMetaMethodSite.java:64)
| Error     at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:112)
| Error     at gant.Gant$_dispatch_closure5.doCall(Gant.groovy:381)
| Error     ... 68 more

**Comment by cc5tudio** [comment]
Seems like this is where the problem is originating from:

Error Caused by: java.lang.NullPointerException
| Error at com.amazonaws.services.elasticbeanstalk.AWSElasticBeanstalkClient.invoke(AWSElasticBeanstalkClient.java:1370)
| Error at com.amazonaws.services.elasticbeanstalk.AWSElasticBeanstalkClient.createStorageLocation(AWSElasticBeanstalkClient.java:371)
| Error at com.amazonaws.services.elasticbeanstalk.AWSElasticBeanstalkClient.createStorageLocation(AWSElasticBeanstalkClient.java:1165)
| Error at com.amazonaws.services.elasticbeanstalk.AWSElasticBeanstalk$createStorageLocation.call(Unknown Source)
| Error at AwsEbDeploy$_run_closure1.doCall(AwsEbDeploy:69)
|

**Comment by kenliu** [comment]
Hi there -

It's blowing up inside the AWS SDK here:

https://github.com/aws/aws-sdk-java/blob/master/src/main/java/com/amazonaws/services/elasticbeanstalk/AWSElasticBeanstalkClient.java

Looks like some issue with credentials. How are you configuring the credentials for the plugin?

**Comment by cc5tudio** [comment]
I configured my credentials using the AWS Toolkit Preferences screen...see
attachment.

**Comment by cc5tudio** [comment]
![screen shot 2013-10-02 at 5 22 29 pm](https://f.cloud.github.com/assets/1259301/1257532/5f717cc6-2ba9-11e3-8c27-3e96158a6afb.png)

**Comment by kenliu** [comment]
Hi - the plugin doesn't provide any integration with the AWS Eclipse plugin. You can configure your credentials using the method specified in the README: https://github.com/kenliu/grails-elastic-beanstalk/blob/master/README.md

**Comment by kenliu** [comment]
created issue #10 to better handle this situation

**Comment by cc5tudio** [comment]
That worked..thanks!  I'm new to Grails so it would help future noobies if there were more explicit instructions on how to set environment variables using Eclipse...
